spring.application.name=agrogestion-api

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TFGRAMON;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=ramon123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.jackson.time-zone=Europe/Madrid
spring.jackson.default-property-inclusion=NON_NULL

server.port=8081

app.jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yVEZHUmFtb25BZ3JvR2VzdGlvblByb2plY3QyMDI0
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-days=7

homeassistant.url=http://suarezdefigueroa.es:8086
homeassistant.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkNjI1MzI1MGRkN2I0OTUwYjMwMzEwMWE4NjJiOTYwOCIsImlhdCI6MTc2MDg5MjExNiwiZXhwIjoyMDc2MjUyMTE2fQ.PCFqgLj880O5hA5ztGO6ON-pGXF1-H3rDWgG3qAtioY
homeassistant.parcela-id=1
homeassistant.intervalo-minutos=5

openweathermap.api-key=3b2c31c9749c569fd36976c0db9d0651
openweathermap.url=https://api.openweathermap.org/data/2.5
openweathermap.unidades=metric

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.tfg.agrogestion=DEBUG
logging.level.org.springframework.security=DEBUG